{
  "securities": [
    {
      "id": "a924ac42-e7e6-4fe9-99a5-26fbe8dd484f",
      "code": "AZG",
      "name": "ازيموت جولد",
      "type": "صندوق",
      "created_at": "2026-06-02T12:39:27.305684+00:00"
    },
    {
      "id": "2178dbc3-388d-45ef-83a5-144c13d69d1c",
      "code": "ETEL",
      "name": "المصرية للإتصالات",
      "type": "سهم",
      "created_at": "2026-06-02T12:39:27.331259+00:00"
    },
    {
      "id": "ec606391-65f2-4207-b8ba-676bbff82d9b",
      "code": "ADIB",
      "name": "مصرف ابوظبي الاسلامي",
      "type": "سهم",
      "created_at": "2026-06-02T12:39:27.35157+00:00"
    },
    {
      "id": "d553daa4-ea20-4459-9488-9a9475a54d59",
      "code": "MTF",
      "name": "مصر للتأمين التكافلي",
      "type": "صندوق",
      "created_at": "2026-06-02T12:39:27.372117+00:00"
    },
    {
      "id": "f5bf1e11-b9ed-4f42-92bc-78a275e83811",
      "code": "BWA",
      "name": "بلتون وفرة",
      "type": "صندوق",
      "created_at": "2026-06-02T12:39:27.392471+00:00"
    },
    {
      "id": "c3b31ca3-d819-48b5-bdc8-53faae4bf408",
      "code": "ABUK",
      "name": "ابوقير للأسمدة",
      "type": "سهم",
      "created_at": "2026-06-02T12:39:27.412843+00:00"
    },
    {
      "id": "b75807f2-cde6-4e2b-8b56-f89d79c05245",
      "code": "CI33",
      "name": "سي اي كابتل - استثمار في مؤشر الشريعة",
      "type": "صندوق",
      "created_at": "2026-06-02T12:39:27.43323+00:00"
    },
    {
      "id": "25dd6732-1ac5-47b8-af8f-7243365848d1",
      "code": "TMGH",
      "name": "طلعت مصطفى",
      "type": "سهم",
      "created_at": "2026-06-02T12:39:27.453584+00:00"
    },
    {
      "id": "3eac5308-9b5c-460b-8764-7a597d59afb1",
      "code": "TS",
      "name": "ثاندر توفير",
      "type": "صندوق",
      "created_at": "2026-06-02T12:39:27.473859+00:00"
    },
    {
      "id": "f49a4cc3-55ff-4368-8c51-8f55b7786580",
      "code": "ARCC",
      "name": "العربية للأسمنت",
      "type": "سهم",
      "created_at": "2026-06-02T12:39:27.494289+00:00"
    },
    {
      "id": "405d6219-3a99-4dfd-ade6-9ae7aefd346f",
      "code": "ADIB 2",
      "name": "مصرف ابوظبي الاسلامي 2",
      "type": "سهم",
      "created_at": "2026-06-02T12:39:27.514623+00:00"
    },
    {
      "id": "5c427306-5fd4-4a73-9adf-07377b4fce76",
      "code": "TS 2",
      "name": "ثاندر توفير 2",
      "type": "صندوق",
      "created_at": "2026-06-02T12:39:27.5348+00:00"
    },
    {
      "id": "925a914c-c19d-45f8-941c-727bebfabc49",
      "code": "MPCO",
      "name": "مصر لإنتاج الاسمدة",
      "type": "سهم",
      "created_at": "2026-06-02T12:39:27.555178+00:00"
    },
    {
      "id": "1a8dd975-ea72-4d76-a361-bf62b444e1bf",
      "code": "DICE",
      "name": "دايس للملابس الجاهزة",
      "type": "سهم",
      "created_at": "2026-06-02T12:39:27.578062+00:00"
    },
    {
      "id": "cce4a8af-007c-460f-ad8e-d4a009e0bae7",
      "code": "TS 3",
      "name": "ثاندر توفير 3",
      "type": "صندوق",
      "created_at": "2026-06-02T12:39:27.598457+00:00"
    },
    {
      "id": "98c085e1-30c9-498b-b75a-788b5cee4630",
      "code": "ORAS",
      "name": "اوراسكوم كونستركشون",
      "type": "سهم",
      "created_at": "2026-06-02T12:39:27.618972+00:00"
    }
  ],
  "purchases": [
    {
      "id": "63e26882-6b68-437f-ab17-6e9832ec44fd",
      "date": "2026-02-10",
      "type": "صندوق",
      "code": "AZG",
      "name": "ازيموت جولد",
      "quantity": 202,
      "price": 25.8,
      "commission": 6.83,
      "total": 5218.43,
      "created_at": "2026-06-02T12:39:27.66074+00:00"
    },
    {
      "id": "22085240-d02e-408f-ada9-3767867f8d7d",
      "date": "2026-02-15",
      "type": "سهم",
      "code": "ETEL",
      "name": "المصرية للإتصالات",
      "quantity": 30,
      "price": 95.8,
      "commission": 6.59,
      "total": 2880.59,
      "created_at": "2026-06-02T12:39:27.682418+00:00"
    },
    {
      "id": "939c6815-48ff-4c9b-a69b-1f5d1824bee3",
      "date": "2026-02-16",
      "type": "سهم",
      "code": "ADIB",
      "name": "مصرف ابوظبي الاسلامي",
      "quantity": 76,
      "price": 40,
      "commission": 6.79,
      "total": 3046.79,
      "created_at": "2026-06-02T12:39:27.702926+00:00"
    },
    {
      "id": "dcce89df-9e15-4f39-89be-adf2a8aaf7c3",
      "date": "2026-02-16",
      "type": "سهم",
      "code": "ETEL",
      "name": "المصرية للإتصالات",
      "quantity": 47,
      "price": 104,
      "commission": 9.11,
      "total": 4897.11,
      "created_at": "2026-06-02T12:39:27.724234+00:00"
    },
    {
      "id": "1b621f2b-1c02-41b7-86e1-3b05609e548b",
      "date": "2026-02-15",
      "type": "صندوق",
      "code": "AZG",
      "name": "ازيموت جولد",
      "quantity": 573,
      "price": 25.83,
      "commission": 16.15,
      "total": 14816.739999999998,
      "created_at": "2026-06-02T12:39:27.744739+00:00"
    },
    {
      "id": "32dab086-9a76-442e-88a8-7628d3af44ae",
      "date": "2026-02-16",
      "type": "صندوق",
      "code": "AZG",
      "name": "ازيموت جولد",
      "quantity": 117,
      "price": 25.64,
      "commission": 4.94,
      "total": 3004.82,
      "created_at": "2026-06-02T12:39:27.76625+00:00"
    },
    {
      "id": "431c431e-53d0-445f-b4b4-e878706bcd69",
      "date": "2026-02-25",
      "type": "سهم",
      "code": "ETEL",
      "name": "المصرية للإتصالات",
      "quantity": 1,
      "price": 87.97,
      "commission": 3.12,
      "total": 91.09,
      "created_at": "2026-06-02T12:39:27.786947+00:00"
    },
    {
      "id": "d5e16d9b-1a38-4994-9503-2d3c17a013eb",
      "date": "2026-02-25",
      "type": "صندوق",
      "code": "MTF",
      "name": "مصر للتأمين التكافلي",
      "quantity": 9,
      "price": 194.26,
      "commission": 3.74,
      "total": 1752.08,
      "created_at": "2026-06-02T12:39:27.80764+00:00"
    },
    {
      "id": "cb375e92-1c49-4614-9ce2-83c39e8c140c",
      "date": "2026-02-26",
      "type": "صندوق",
      "code": "AZG",
      "name": "ازيموت جولد",
      "quantity": 22,
      "price": 26.91,
      "commission": 2.54,
      "total": 594.56,
      "created_at": "2026-06-02T12:39:27.828307+00:00"
    },
    {
      "id": "64d76b69-8651-4f20-a3b1-86c364d3e440",
      "date": "2026-02-25",
      "type": "صندوق",
      "code": "BWA",
      "name": "بلتون وفرة",
      "quantity": 2085,
      "price": 1.705,
      "commission": 5.345,
      "total": 3560.27,
      "created_at": "2026-06-02T12:39:27.8489+00:00"
    },
    {
      "id": "6c35ba40-636f-4c56-9f3b-b4784a3f040c",
      "date": "2026-03-03",
      "type": "صندوق",
      "code": "BWA",
      "name": "بلتون وفرة",
      "quantity": 7,
      "price": 1.678,
      "commission": 2.014,
      "total": 13.759999999999998,
      "created_at": "2026-06-02T12:39:27.869153+00:00"
    },
    {
      "id": "3d2402b7-6054-4572-b20e-3df036fa5421",
      "date": "2026-03-11",
      "type": "سهم",
      "code": "ETEL",
      "name": "المصرية للإتصالات",
      "quantity": 119,
      "price": 84.6,
      "commission": 15.59,
      "total": 10082.99,
      "created_at": "2026-06-02T12:39:27.889583+00:00"
    },
    {
      "id": "87f1eec7-c507-440f-99c1-08071bea5e7f",
      "date": "2026-03-11",
      "type": "سهم",
      "code": "ABUK",
      "name": "ابوقير للأسمدة",
      "quantity": 125,
      "price": 80.9,
      "commission": 15.64,
      "total": 10128.14,
      "created_at": "2026-06-02T12:39:27.910162+00:00"
    },
    {
      "id": "d64b3267-c140-4473-81d5-ecf2c574fe13",
      "date": "2026-03-11",
      "type": "سهم",
      "code": "ADIB",
      "name": "مصرف ابوظبي الاسلامي",
      "quantity": 255,
      "price": 39.25,
      "commission": 15.51,
      "total": 10024.26,
      "created_at": "2026-06-02T12:39:27.930806+00:00"
    },
    {
      "id": "8be868d5-9b52-4c5e-9115-3855b6fe15a9",
      "date": "2026-03-12",
      "type": "سهم",
      "code": "ETEL",
      "name": "المصرية للإتصالات",
      "quantity": 4,
      "price": 84.7,
      "commission": 3.42,
      "total": 342.22,
      "created_at": "2026-06-02T12:39:27.951237+00:00"
    },
    {
      "id": "f8b26e5c-ebdc-4901-8fbd-24d2f57f953f",
      "date": "2026-03-12",
      "type": "صندوق",
      "code": "BWA",
      "name": "بلتون وفرة",
      "quantity": 3925,
      "price": 1.681,
      "commission": 9.735,
      "total": 6607.66,
      "created_at": "2026-06-02T12:39:27.971525+00:00"
    },
    {
      "id": "3a396c5f-ce46-4b68-b79c-e6357fd68e1b",
      "date": "2026-03-12",
      "type": "صندوق",
      "code": "AZG",
      "name": "ازيموت جولد",
      "quantity": 119,
      "price": 28.508,
      "commission": 5.338,
      "total": 3397.79,
      "created_at": "2026-06-02T12:39:27.991918+00:00"
    },
    {
      "id": "4a90b1b9-65a2-4638-a0b4-67253d4fcc95",
      "date": "2026-03-12",
      "type": "صندوق",
      "code": "CI33",
      "name": "سي اي كابتل - استثمار في مؤشر الشريعة",
      "quantity": 560,
      "price": 17.324,
      "commission": 11.71,
      "total": 9713.15,
      "created_at": "2026-06-02T12:39:28.0121+00:00"
    },
    {
      "id": "4c6ef988-2c11-4fa5-8f8d-eb1cc6a8316c",
      "date": "2026-03-16",
      "type": "سهم",
      "code": "ADIB",
      "name": "مصرف ابوظبي الاسلامي",
      "quantity": 2,
      "price": 37.49,
      "commission": 3.1,
      "total": 78.08,
      "created_at": "2026-06-02T12:39:28.032371+00:00"
    },
    {
      "id": "33eea8e4-13ba-4e82-a759-74bd62918b20",
      "date": "2026-03-17",
      "type": "سهم",
      "code": "ETEL",
      "name": "المصرية للإتصالات",
      "quantity": 141,
      "price": 83.31,
      "commission": 22.31,
      "total": 11769.02,
      "created_at": "2026-06-02T12:39:28.05272+00:00"
    },
    {
      "id": "27cd9237-39ea-4666-8f8a-37f97e9352a8",
      "date": "2026-03-17",
      "type": "سهم",
      "code": "TMGH",
      "name": "طلعت مصطفى",
      "quantity": 262,
      "price": 76.49,
      "commission": 29.25,
      "total": 20069.629999999997,
      "created_at": "2026-06-02T12:39:28.073035+00:00"
    },
    {
      "id": "18b36efa-10b0-4d4b-adc5-2fda2b8f21b7",
      "date": "2026-03-18",
      "type": "صندوق",
      "code": "MTF",
      "name": "مصر للتأمين التكافلي",
      "quantity": 50,
      "price": 196.263,
      "commission": 11.8,
      "total": 9824.949999999999,
      "created_at": "2026-06-02T12:39:28.093297+00:00"
    },
    {
      "id": "0e1ac31b-bf37-47f7-a211-4ed1a74ed82a",
      "date": "2026-03-24",
      "type": "سهم",
      "code": "ETEL",
      "name": "المصرية للإتصالات",
      "quantity": 25,
      "price": 82.98,
      "commission": 5.59,
      "total": 2080.09,
      "created_at": "2026-06-02T12:39:28.113685+00:00"
    },
    {
      "id": "9b07f3cb-c8c4-454d-9e97-9fd0cfbccdd9",
      "date": "2026-03-25",
      "type": "صندوق",
      "code": "TS",
      "name": "ثاندر توفير",
      "quantity": 8134,
      "price": 1.22925989672,
      "commission": 0,
      "total": 9998.799999920479,
      "created_at": "2026-06-02T12:39:28.133972+00:00"
    },
    {
      "id": "69f4a75b-29bc-4bfa-84c2-42ad1dbead81",
      "date": "2026-03-25",
      "type": "صندوق",
      "code": "AZG",
      "name": "ازيموت جولد",
      "quantity": 113,
      "price": 26.188,
      "commission": 4.956,
      "total": 2964.2,
      "created_at": "2026-06-02T12:39:28.154851+00:00"
    },
    {
      "id": "9207a069-48fc-4fdf-889e-ddbe2f95c35b",
      "date": "2026-03-26",
      "type": "سهم",
      "code": "TMGH",
      "name": "طلعت مصطفى",
      "quantity": 127,
      "price": 79.35,
      "commission": 15.6,
      "total": 10093.05,
      "created_at": "2026-06-02T12:39:28.175094+00:00"
    },
    {
      "id": "50d5a742-03f4-48f6-a411-424801315517",
      "date": "2026-03-26",
      "type": "سهم",
      "code": "ARCC",
      "name": "العربية للأسمنت",
      "quantity": 231,
      "price": 50.72,
      "commission": 20.72,
      "total": 11737.039999999999,
      "created_at": "2026-06-02T12:39:28.195429+00:00"
    },
    {
      "id": "f23d887d-d4b8-4085-a953-e1a253aafc5e",
      "date": "2026-04-15",
      "type": "سهم",
      "code": "ARCC",
      "name": "العربية للأسمنت",
      "quantity": 98,
      "price": 54.9,
      "commission": 9.73,
      "total": 5389.929999999999,
      "created_at": "2026-06-02T12:39:28.215742+00:00"
    },
    {
      "id": "9e59bc03-84d0-4d5b-8b1b-9bba578529d6",
      "date": "2026-04-16",
      "type": "صندوق",
      "code": "BWA",
      "name": "بلتون وفرة",
      "quantity": 2698,
      "price": 1.786,
      "commission": 6.012,
      "total": 4824.639999999999,
      "created_at": "2026-06-02T12:39:28.23603+00:00"
    },
    {
      "id": "55c9406e-a7cc-45c6-a1cc-5f6f5286f483",
      "date": "2026-05-04",
      "type": "صندوق",
      "code": "BWA",
      "name": "بلتون وفرة",
      "quantity": 4612,
      "price": 1.887,
      "commission": 12.826,
      "total": 8715.669999999998,
      "created_at": "2026-06-02T12:39:28.256474+00:00"
    },
    {
      "id": "95c4c7e7-df77-41c0-981a-096d393a74d8",
      "date": "2026-05-04",
      "type": "صندوق",
      "code": "MTF",
      "name": "مصر للتأمين التكافلي",
      "quantity": 81,
      "price": 200.735,
      "commission": 18.225,
      "total": 16277.760000000002,
      "created_at": "2026-06-02T12:39:28.276808+00:00"
    },
    {
      "id": "c142a81d-3956-46de-b8e1-fbbe7315c160",
      "date": "2026-05-17",
      "type": "سهم",
      "code": "ADIB 2",
      "name": "مصرف ابوظبي الاسلامي 2",
      "quantity": 213,
      "price": 46.9,
      "commission": 15.49,
      "total": 10005.189999999999,
      "created_at": "2026-06-02T12:39:28.297294+00:00"
    },
    {
      "id": "879c7162-beb1-4f44-8afc-cf8210a5014e",
      "date": "2026-05-18",
      "type": "صندوق",
      "code": "BWA",
      "name": "بلتون وفرة",
      "quantity": 3274,
      "price": 1.918,
      "commission": 8.28,
      "total": 6287.58,
      "created_at": "2026-06-02T12:39:28.317927+00:00"
    },
    {
      "id": "4c933f66-0265-437f-9ab6-3adc83017cfb",
      "date": "2026-05-18",
      "type": "صندوق",
      "code": "TS 2",
      "name": "ثاندر توفير 2",
      "quantity": 9609,
      "price": 1.25878967634,
      "commission": 0,
      "total": 12095.70999995106,
      "created_at": "2026-06-02T12:39:28.338621+00:00"
    },
    {
      "id": "24e4b6f3-325d-4c3c-8f7e-aa7258120da0",
      "date": "2026-05-20",
      "type": "سهم",
      "code": "ADIB 2",
      "name": "مصرف ابوظبي الاسلامي 2",
      "quantity": 43,
      "price": 46.27,
      "commission": 5.49,
      "total": 1995.1000000000001,
      "created_at": "2026-06-02T12:39:28.359378+00:00"
    },
    {
      "id": "c6b50a8e-f1fd-404b-8c15-6c71fa06c58d",
      "date": "2026-05-20",
      "type": "سهم",
      "code": "MPCO",
      "name": "مصر لإنتاج الاسمدة",
      "quantity": 48,
      "price": 43.55,
      "commission": 5.61,
      "total": 2096.0099999999998,
      "created_at": "2026-06-02T12:39:28.37966+00:00"
    },
    {
      "id": "b4227220-6c2f-4338-9072-ebe29aeccdca",
      "date": "2026-05-20",
      "type": "سهم",
      "code": "DICE",
      "name": "دايس للملابس الجاهزة",
      "quantity": 1136,
      "price": 1.76,
      "commission": 5.5,
      "total": 2004.86,
      "created_at": "2026-06-02T12:39:28.400045+00:00"
    },
    {
      "id": "08e26fc2-ed4a-4dc7-a329-d70165ded86b",
      "date": "2026-05-21",
      "type": "سهم",
      "code": "DICE",
      "name": "دايس للملابس الجاهزة",
      "quantity": 581,
      "price": 1.72,
      "commission": 4.25,
      "total": 1003.5699999999999,
      "created_at": "2026-06-02T12:39:28.420415+00:00"
    },
    {
      "id": "f9d0ee18-cc00-4f9a-8985-89a24c5f9523",
      "date": "2026-05-21",
      "type": "سهم",
      "code": "MPCO",
      "name": "مصر لإنتاج الاسمدة",
      "quantity": 23,
      "price": 43.25,
      "commission": 4.24,
      "total": 998.99,
      "created_at": "2026-06-02T12:39:28.440805+00:00"
    },
    {
      "id": "9bd17212-6c99-4c7c-a8e6-945da6375afc",
      "date": "2026-05-21",
      "type": "سهم",
      "code": "ADIB 2",
      "name": "مصرف ابوظبي الاسلامي 2",
      "quantity": 21,
      "price": 46.35,
      "commission": 4.22,
      "total": 977.57,
      "created_at": "2026-06-02T12:39:28.461202+00:00"
    },
    {
      "id": "cbd16da8-2f70-4145-9a0e-28e5973f1c19",
      "date": "2026-05-24",
      "type": "صندوق",
      "code": "TS 3",
      "name": "ثاندر توفير 3",
      "quantity": 6893,
      "price": 1.26218047294,
      "commission": 0,
      "total": 8700.20999997542,
      "created_at": "2026-06-02T12:39:28.481506+00:00"
    },
    {
      "id": "e5c64a43-007a-4b46-aca2-b32288711d8c",
      "date": "2026-06-01",
      "type": "سهم",
      "code": "ORAS",
      "name": "اوراسكوم كونستركشون",
      "quantity": 5,
      "price": 746.99,
      "commission": 7.66,
      "total": 3742.6099999999997,
      "created_at": "2026-06-02T12:39:28.501758+00:00"
    }
  ],
  "sales": [
    {
      "id": "ce8d786c-a4f2-4743-b7f8-dcd3142e0809",
      "date": "2026-03-25",
      "type": "سهم",
      "code": "ABUK",
      "name": "ابوقير للأسمدة",
      "quantity": 125,
      "sell_price": 92.5,
      "avg_buy_price": 81.02512,
      "commission": 17.46,
      "total_sell": 11545.04,
      "net_profit": 1416.9000000000015,
      "profit_pct": 13.989735528932275,
      "created_at": "2026-06-02T12:39:28.522264+00:00"
    },
    {
      "id": "4c706634-794f-4748-96a1-da425119991a",
      "date": "2026-03-26",
      "type": "صندوق",
      "code": "TS",
      "name": "ثاندر توفير",
      "quantity": 8134,
      "sell_price": 1.22980944184,
      "avg_buy_price": 1.22925989672,
      "commission": 0,
      "total_sell": 10003.26999992656,
      "net_profit": 4.470000006082046,
      "profit_pct": 0.044705364704940555,
      "created_at": "2026-06-02T12:39:28.54399+00:00"
    },
    {
      "id": "2ab9b6d2-9cea-4d75-9e13-121601451e5d",
      "date": "2026-04-15",
      "type": "صندوق",
      "code": "CI33",
      "name": "سي اي كابتل - استثمار في مؤشر الشريعة",
      "quantity": 560,
      "sell_price": 18.208,
      "avg_buy_price": 17.344910714285714,
      "commission": 12.15,
      "total_sell": 10184.33,
      "net_profit": 471.1800000000003,
      "profit_pct": 4.850949486006088,
      "created_at": "2026-06-02T12:39:28.565462+00:00"
    },
    {
      "id": "181656f0-1918-46d9-9ce9-42da05d4c845",
      "date": "2026-05-04",
      "type": "سهم",
      "code": "ADIB",
      "name": "مصرف ابوظبي الاسلامي",
      "quantity": 333,
      "sell_price": 49.49,
      "avg_buy_price": 39.48687687687688,
      "commission": 24.6,
      "total_sell": 16455.570000000003,
      "net_profit": 3306.4400000000023,
      "profit_pct": 25.14569404972041,
      "created_at": "2026-06-02T12:39:28.585961+00:00"
    },
    {
      "id": "e4c28496-a874-4ac8-8c8b-22fbc468ec36",
      "date": "2026-05-17",
      "type": "صندوق",
      "code": "MTF",
      "name": "مصر للتأمين التكافلي",
      "quantity": 140,
      "sell_price": 201.771785714,
      "avg_buy_price": 198.96278571428573,
      "commission": 30.28,
      "total_sell": 28217.76999996,
      "net_profit": 393.26,
      "profit_pct": 1.4118218087445642,
      "created_at": "2026-06-02T12:39:28.60635+00:00"
    },
    {
      "id": "969bceb2-bb6b-46bc-bba7-585935e4fd18",
      "date": "2026-05-20",
      "type": "صندوق",
      "code": "TS 2",
      "name": "ثاندر توفير 2",
      "quantity": 1189,
      "sell_price": 1.25993271656,
      "avg_buy_price": 1.25878967634,
      "commission": 0,
      "total_sell": 1498.05999998984,
      "net_profit": 1.3590748215799522,
      "profit_pct": 0.09080470244428854,
      "created_at": "2026-06-02T12:39:28.62674+00:00"
    },
    {
      "id": "480543a5-cd0f-42b3-9331-1c185b0c007f",
      "date": "2026-05-21",
      "type": "صندوق",
      "code": "TS 2",
      "name": "ثاندر توفير 2",
      "quantity": 8420,
      "sell_price": 1.26050950118,
      "avg_buy_price": 1.25878967634,
      "commission": 0,
      "total_sell": 10613.4899999356,
      "net_profit": 14.48092515280041,
      "profit_pct": 0.13662527365179333,
      "created_at": "2026-06-02T12:39:28.647362+00:00"
    },
    {
      "id": "f1a9caf5-a68b-470a-96dc-df3255de4b2e",
      "date": "2026-05-25",
      "type": "صندوق",
      "code": "TS 3",
      "name": "ثاندر توفير 3",
      "quantity": 157,
      "sell_price": 1.2627388535,
      "avg_buy_price": 1.26218047294,
      "commission": 0,
      "total_sell": 198.24999999949998,
      "net_profit": 0.08766574791999915,
      "profit_pct": 0.04423935974063657,
      "created_at": "2026-06-02T12:39:28.667818+00:00"
    }
  ],
  "dividends": [
    {
      "id": "6a2fd154-c2a5-4f2b-bc90-37e8dc3bb23c",
      "date": "2026-04-19",
      "code": "ARCC",
      "name": "العربية للأسمنت",
      "quantity": 231,
      "coupon_per_share": 5.34,
      "gov_commission": 61.677,
      "net_profit": 1171.863,
      "created_at": "2026-06-02T12:39:28.688247+00:00"
    },
    {
      "id": "4dcf6263-a98c-49f4-8f30-84e1a376f950",
      "date": "2026-04-30",
      "code": "ETEL",
      "name": "المصرية للإتصالات",
      "quantity": 367,
      "coupon_per_share": 1.5,
      "gov_commission": 27.525000000000002,
      "net_profit": 522.975,
      "created_at": "2026-06-02T12:39:28.709688+00:00"
    },
    {
      "id": "649a8af2-4593-4917-aef7-ef9b5b369f29",
      "date": "2026-05-21",
      "code": "TMGH",
      "name": "طلعت مصطفى",
      "quantity": 389,
      "coupon_per_share": 0.15,
      "gov_commission": 2.9175,
      "net_profit": 55.4325,
      "created_at": "2026-06-02T12:39:28.730208+00:00"
    }
  ],
  "partners": [
    {
      "id": "af79c8ed-06dc-4268-9b7b-16de96e6b340",
      "name": "علاء",
      "capital": 222900,
      "created_at": "2026-06-02T12:39:27.639343+00:00"
    },
    {
      "id": "d20c9a05-ebec-4fac-8179-2d14179bf2fb",
      "name": "محمد",
      "capital": 36800,
      "created_at": "2026-06-02T12:39:27.639343+00:00"
    }
  ]
}
